name: m_statistics
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0-19.0.dev <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  path_provider: ^2.0.13
  assets_audio_player: ^3.1.1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
